title: Bioinformatics Tutorials  # Your site's title
description: Welcome to my personal page! # A brief description
author: Bruno Santos  # Your name
theme: jekyll-theme-cayman # Or another theme you want to use
